"""create info_specs

Revision ID: 938ebc034b82
Revises: d8899e01cbd0
Create Date: 2026-05-03 20:32:17.827801

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "938ebc034b82"
down_revision: str | Sequence[str] | None = "d8899e01cbd0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "info_specs",
        sa.Column("info_spec_id", sa.String(length=26), nullable=False),
        sa.Column("info_item_id", sa.String(length=26), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["info_item_id"],
            ["information.info_items.info_item_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("info_spec_id"),
        schema="information",
    )
    op.create_index(
        op.f("ix_information_info_specs_info_item_id"),
        "info_specs",
        ["info_item_id"],
        unique=False,
        schema="information",
    )
    op.create_index(
        "uq_info_specs_active_priority_per_item",
        "info_specs",
        ["info_item_id", "priority"],
        unique=True,
        schema="information",
        postgresql_where=sa.text("active"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_info_specs_active_priority_per_item",
        table_name="info_specs",
        schema="information",
        postgresql_where=sa.text("active"),
    )
    op.drop_index(
        op.f("ix_information_info_specs_info_item_id"),
        table_name="info_specs",
        schema="information",
    )
    op.drop_table("info_specs", schema="information")
    # ### end Alembic commands ###
