"""add snapshots, snapshot_chunks, and changes tables

Revision ID: 09c9f5922650
Revises: 43ed48a9bd11
Create Date: 2026-03-20 22:57:46.954359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09c9f5922650'
down_revision: Union[str, Sequence[str], None] = '43ed48a9bd11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snapshots',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('watch_id', sa.String(length=26), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('simhash', sa.BigInteger(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('text_path', sa.Text(), nullable=False),
    sa.Column('storage_backend', sa.String(length=20), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('text_bytes', sa.BigInteger(), nullable=False),
    sa.Column('fetch_duration_ms', sa.Integer(), nullable=False),
    sa.Column('fetcher_used', sa.String(length=50), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['watch_id'], ['watches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('changes',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('watch_id', sa.String(length=26), nullable=False),
    sa.Column('previous_snapshot_id', sa.String(length=26), nullable=False),
    sa.Column('current_snapshot_id', sa.String(length=26), nullable=False),
    sa.Column('change_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_snapshot_id'], ['snapshots.id'], ),
    sa.ForeignKeyConstraint(['previous_snapshot_id'], ['snapshots.id'], ),
    sa.ForeignKeyConstraint(['watch_id'], ['watches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshot_chunks',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('snapshot_id', sa.String(length=26), nullable=False),
    sa.Column('chunk_index', sa.SmallInteger(), nullable=False),
    sa.Column('chunk_type', sa.String(length=20), nullable=False),
    sa.Column('chunk_label', sa.String(length=255), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('simhash', sa.BigInteger(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snapshot_chunks')
    op.drop_table('changes')
    op.drop_table('snapshots')
    # ### end Alembic commands ###
