"""step 6 drop watch cols rename domain_suspended drop last_known_revisions pending_source_revisions

Revision ID: 2b7c99117877
Revises: a1b2c3d4e5f6
Create Date: 2026-06-08 21:20:53.669304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b7c99117877'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_source_revisions_info_source_id'), table_name='pending_source_revisions')
    op.drop_index(op.f('ix_pending_source_revisions_next_attempt'), table_name='pending_source_revisions', postgresql_where='(attempts < 10)')
    op.drop_table('pending_source_revisions')
    op.drop_table('last_known_revisions')
    op.drop_index(op.f('ix_change_revisions_watched_item_captured_at'), table_name='change_revisions')
    op.create_index(op.f('ix_change_revisions_watched_item_id'), 'change_revisions', ['watched_item_id'], unique=False)
    op.drop_index(op.f('ix_pending_archiver_sync_next_attempt'), table_name='pending_archiver_sync', postgresql_where='(attempts < 10)')
    op.create_index(op.f('ix_pending_archiver_sync_watched_item_id'), 'pending_archiver_sync', ['watched_item_id'], unique=False)
    op.add_column('watches', sa.Column('suspended_by_domain', sa.Boolean(), server_default='false', nullable=False))
    op.drop_index(op.f('ix_watches_info_item_id'), table_name='watches')
    op.drop_index(op.f('ix_watches_target_info_source_id'), table_name='watches')
    op.drop_column('watches', 'info_item_id')
    op.drop_column('watches', 'domain_suspended')
    op.drop_column('watches', 'health_status')
    op.drop_column('watches', 'target_info_source_id')
    op.drop_column('watches', 'effective_url')
    op.drop_column('watches', 'last_checked_at')
    op.drop_column('watches', 'last_changed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watches', sa.Column('last_changed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('watches', sa.Column('last_checked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('watches', sa.Column('effective_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('watches', sa.Column('target_info_source_id', sa.VARCHAR(length=26), autoincrement=False, nullable=True))
    op.add_column('watches', sa.Column('health_status', sa.VARCHAR(length=10), server_default=sa.text("'unknown'::character varying"), autoincrement=False, nullable=False))
    op.add_column('watches', sa.Column('domain_suspended', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('watches', sa.Column('info_item_id', sa.VARCHAR(length=26), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_watches_target_info_source_id'), 'watches', ['target_info_source_id'], unique=False)
    op.create_index(op.f('ix_watches_info_item_id'), 'watches', ['info_item_id'], unique=False)
    op.drop_column('watches', 'suspended_by_domain')
    op.drop_index(op.f('ix_pending_archiver_sync_watched_item_id'), table_name='pending_archiver_sync')
    op.create_index(op.f('ix_pending_archiver_sync_next_attempt'), 'pending_archiver_sync', ['next_attempt_at'], unique=False, postgresql_where='(attempts < 10)')
    op.drop_index(op.f('ix_change_revisions_watched_item_id'), table_name='change_revisions')
    op.create_index(op.f('ix_change_revisions_watched_item_captured_at'), 'change_revisions', ['watched_item_id', sa.literal_column('captured_at DESC')], unique=False)
    op.create_table('last_known_revisions',
    sa.Column('info_source_id', sa.VARCHAR(length=26), autoincrement=False, nullable=False),
    sa.Column('content_fingerprint', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source_revision_id', sa.VARCHAR(length=26), autoincrement=False, nullable=False),
    sa.Column('captured_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('info_source_id', name=op.f('last_known_revisions_pkey'))
    )
    op.create_table('pending_source_revisions',
    sa.Column('id', sa.VARCHAR(length=26), autoincrement=False, nullable=False),
    sa.Column('info_source_id', sa.VARCHAR(length=26), autoincrement=False, nullable=False),
    sa.Column('content_fingerprint', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('captured_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('content_size_bytes', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('content_media_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content_cache_uri', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content_cache_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('attempts', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('last_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('next_attempt_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pending_source_revisions_pkey')),
    sa.UniqueConstraint('info_source_id', 'content_fingerprint', name=op.f('uq_pending_source_revisions_source_fingerprint'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_pending_source_revisions_next_attempt'), 'pending_source_revisions', ['next_attempt_at'], unique=False, postgresql_where='(attempts < 10)')
    op.create_index(op.f('ix_pending_source_revisions_info_source_id'), 'pending_source_revisions', ['info_source_id'], unique=False)
    # ### end Alembic commands ###
