"""watched_items.last_error_notified_at: re-notify a persistent ERROR (#71)

Revision ID: 36358e2f5ad4
Revises: 78606286a887
Create Date: 2026-10-09

Autogenerated against a scratch database (#259); the backfill is hand-written.

**The backfill starts the clock on items already in ERROR.** The re-notify gate
reads a NULL stamp on an ERROR item as due, so without it every such item would
re-send ``WATCH_ERROR`` on its next failed check — a burst at deploy. Stamped
with the migration's time, their first reminder comes one
``WATCHER_ERROR_RENOTIFY_INTERVAL`` later. When they were really last told is
not recorded anywhere, so a reminder's ``previously_notified_at`` names this
migration, once.

**Deploy order: the repo default, migrate then restart.** Old code ignores the
column. New code against an unmigrated table fails every load of a WatchedItem.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "36358e2f5ad4"
down_revision: str | Sequence[str] | None = "78606286a887"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def backfill_error_items() -> None:
    """Stamp every unstamped item already in ERROR with the migration's time."""
    op.execute(
        "UPDATE watched_items SET last_error_notified_at = now()"
        " WHERE health_status = 'error' AND last_error_notified_at IS NULL"
    )


def upgrade() -> None:
    """Add the column, then start the clock on items already in ERROR."""
    op.add_column(
        "watched_items",
        sa.Column("last_error_notified_at", sa.DateTime(timezone=True), nullable=True),
    )
    backfill_error_items()


def downgrade() -> None:
    """Drop the column; nothing else reads it."""
    op.drop_column("watched_items", "last_error_notified_at")
