"""change content_type to varchar20

Revision ID: 43ed48a9bd11
Revises: 5ffcb2894ab6
Create Date: 2026-03-20 21:15:51.639855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43ed48a9bd11'
down_revision: Union[str, Sequence[str], None] = '5ffcb2894ab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('watches', 'content_type',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('watches', 'content_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=4),
               existing_nullable=False)
    # ### end Alembic commands ###
