"""process_commands: drop the shadow leg's columns (#350), index output_digest (#345)

Revision ID: 89e0c7725367
Revises: 36358e2f5ad4
Create Date: 2026-10-10

Autogenerated against a scratch database (#259). One table, one window.

* **The five ``local_*`` / ``shadow_*`` columns go with the shadow leg.** They
  were the switch gate's only per-row record; #326's comments carry the full
  verdict — 87/87 shadow lineages matched, then the 80/80 processor-decided
  soak — so dropping them loses nothing that is not already written down.
* **``ix_process_commands_output_digest``** serves the change diff's text
  lookup (``stored_text_location``): partial on that query's own predicate, so
  it holds only answers the lookup can return.

**Deploy order: restart, then migrate** (docs/MIGRATIONS.md, the #261
precedent). The old process maps the dropped columns, so migrating first would
fail every ``process_commands`` query it makes until the restart landed. New
code against the unmigrated table is safe: nullable columns it never names, an
index it does not need to be correct.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "89e0c7725367"
down_revision: str | Sequence[str] | None = "36358e2f5ad4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_STORED_TEXT = sa.text("status = 'completed' AND output_uri IS NOT NULL")
_SHADOW_COLUMNS = (
    ("local_outcome", sa.String(length=20)),
    ("local_fingerprint", sa.Text()),
    ("local_spec_fingerprint", sa.Text()),
    ("shadow_verdict", sa.String(length=20)),
    ("shadow_detail", sa.Text()),
)


def upgrade() -> None:
    """Index the diff lookup, then drop the shadow leg's columns."""
    op.create_index(
        "ix_process_commands_output_digest",
        "process_commands",
        ["output_digest"],
        unique=False,
        postgresql_where=_STORED_TEXT,
    )
    for name, _type in _SHADOW_COLUMNS:
        op.drop_column("process_commands", name)


def downgrade() -> None:
    """Restore the columns empty — their values are gone — and drop the index."""
    for name, type_ in reversed(_SHADOW_COLUMNS):
        op.add_column("process_commands", sa.Column(name, type_, nullable=True))
    op.drop_index(
        "ix_process_commands_output_digest",
        table_name="process_commands",
        postgresql_where=_STORED_TEXT,
    )
