"""carry observation provenance on the archiver outbox (#253)

Revision ID: 9c1d4b7ea822
Revises: 7efe5778fb3b
Create Date: 2026-08-09 19:22:00.000000

``SourceRevisionObservedEvent`` (cannobserv#301) needs values the outbox row has
never held: the blob facts as Replicator stated them, the media type of the
extracted content, and the identity of the spec it was extracted under. All six
are snapshotted at enqueue time rather than joined from ``fetch_commands`` at
drain time — the command row's lifecycle is not the outbox row's, and the apply
path holds the values already.

Hand-written rather than autogenerated: this VM's ``watcher`` role cannot create
the scratch database an autogenerate run needs, and the change is six additive
columns. ``alembic check`` in CI (#234) is the drift guard.

All nullable, no backfill. Rows enqueued before this migration drain over the
HTTP POST off ``content_cache_uri``, which is untouched here — the publisher
swap is a later step, and until it lands nothing reads these columns. NULL is
therefore the truthful value for an existing row, not a gap to fill with
invented data.

``command_id`` is String(26) to match ``fetch_commands.command_id`` (a ULID),
deliberately without an FK: the outbox row must outlive the command row it came
from, since delivery to Archiver is the thing being guaranteed.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9c1d4b7ea822"
down_revision: str | Sequence[str] | None = "7efe5778fb3b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "pending_archiver_sync",
        sa.Column("command_id", sa.String(length=26), nullable=True),
    )
    op.add_column(
        "pending_archiver_sync",
        sa.Column("blob_uri", sa.Text(), nullable=True),
    )
    op.add_column(
        "pending_archiver_sync",
        sa.Column("blob_expires_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "pending_archiver_sync",
        sa.Column("source_media_type", sa.Text(), nullable=True),
    )
    op.add_column(
        "pending_archiver_sync",
        sa.Column("content_media_type", sa.Text(), nullable=True),
    )
    op.add_column(
        "pending_archiver_sync",
        sa.Column("spec_fingerprint", sa.Text(), nullable=True),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("pending_archiver_sync", "spec_fingerprint")
    op.drop_column("pending_archiver_sync", "content_media_type")
    op.drop_column("pending_archiver_sync", "source_media_type")
    op.drop_column("pending_archiver_sync", "blob_expires_at")
    op.drop_column("pending_archiver_sync", "blob_uri")
    op.drop_column("pending_archiver_sync", "command_id")
