"""add last_checked_at to watches

Revision ID: 9ea381c8ff08
Revises: 09c9f5922650
Create Date: 2026-03-21 00:29:17.178673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ea381c8ff08'
down_revision: Union[str, Sequence[str], None] = '09c9f5922650'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watches', sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watches', 'last_checked_at')
    # ### end Alembic commands ###
