"""registry announcement reconcile state (#254)

Revision ID: b3f1a7c50d94
Revises: 32140463c26c
Create Date: 2026-08-11 19:40:00.000000

The state the ``info.registry`` reconcile needs, and could not borrow from an
existing column without breaking something.

``announced_schedule_config`` is the registry's cadence policy, the new top tier
of schedule resolution. It is *not* ``default_schedule_config`` on purpose: that
column already has two writers — the operator and ``schedule_tick``'s
``reduce_frequency`` post-action — so reconciling into it would let the hourly
snapshot silently revert every throttle, and would contaminate the values
CannObserv/archiver#150 imports out of Watcher before the SDK is deleted. NULL
carries the contract's delegation case (``{"schema_version": 1}`` with no
``interval``, cannobserv#324): fall to the per-domain default.

``throttle_floor_interval`` is where ``reduce_frequency`` moves to. A throttle is
protective mechanism rather than cadence policy, so it applies as a floor over
the resolved interval instead of competing for a tier — it survives
reconciliation and can only slow an item, never speed one past the announced
cadence.

``applied_generation`` is the ordering guard: apply iff ``generation >`` stored.
NULL means no announcement has ever been applied, which every generation exceeds
(including 0 — the contract permits it and rejects only negatives).

``revoked_info_items`` keeps that guard total across a delete. Revocation removes
the WatchedItem row and would take ``applied_generation`` with it, so a stale
live announcement arriving after the tombstone — the exact reordering
``generation`` exists to defeat, since the producer's outbox drain reorders under
retry — would find no row, have nothing to compare against, and resurrect a
retired item. Boot replay from ``0-0`` is the same shape, milder.

Hand-written rather than autogenerated: this VM's ``watcher`` role cannot create
the scratch database an autogenerate run needs. ``alembic check`` in CI (#234) is
the drift guard.

No backfill, and none is possible: nothing has been published to
``info.registry`` yet (CannObserv/archiver#141's producer is not live), so NULL
is the truthful value on every existing row rather than a gap to fill with
invented data. Existing items keep resolving through the local chain exactly as
they do today until their first announcement lands.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b3f1a7c50d94"
down_revision: str | Sequence[str] | None = "32140463c26c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "watched_items",
        sa.Column("announced_schedule_config", postgresql.JSONB(), nullable=True),
    )
    op.add_column(
        "watched_items",
        sa.Column("throttle_floor_interval", sa.String(length=16), nullable=True),
    )
    op.add_column(
        "watched_items",
        sa.Column("applied_generation", sa.BigInteger(), nullable=True),
    )
    op.create_table(
        "revoked_info_items",
        sa.Column("info_item_id", sa.String(length=26), nullable=False),
        sa.Column("generation", sa.BigInteger(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("info_item_id"),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table("revoked_info_items")
    op.drop_column("watched_items", "applied_generation")
    op.drop_column("watched_items", "throttle_floor_interval")
    op.drop_column("watched_items", "announced_schedule_config")
