"""add fetch_commands (#241 Phase 4 step 1)

Revision ID: bb01df9e79c8
Revises: c398e0917f16
Create Date: 2026-08-06 15:42:08.606693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb01df9e79c8'
down_revision: Union[str, Sequence[str], None] = 'c398e0917f16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fetch_commands',
    sa.Column('command_id', sa.String(length=26), nullable=False),
    sa.Column('intent_id', sa.String(length=26), nullable=False),
    sa.Column('watched_item_id', sa.String(length=26), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reissue_count', sa.Integer(), nullable=False),
    sa.Column('fact_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_fingerprint', sa.Text(), nullable=True),
    sa.Column('blob_uri', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('media_type', sa.Text(), nullable=True),
    sa.Column('content_type_raw', sa.Text(), nullable=True),
    sa.Column('final_url', sa.Text(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('failure_detail', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['watched_item_id'], ['watched_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('command_id')
    )
    op.create_index('ix_fetch_commands_open', 'fetch_commands', ['watched_item_id'], unique=False, postgresql_where=sa.text("status IN ('pending_publish', 'in_flight')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fetch_commands_open', table_name='fetch_commands', postgresql_where=sa.text("status IN ('pending_publish', 'in_flight')"))
    op.drop_table('fetch_commands')
    # ### end Alembic commands ###
