"""require the Archiver InfoItem/InfoSource links (#251)

Revision ID: d5a71c93e0f2
Revises: bb01df9e79c8
Create Date: 2026-08-07 00:00:00.000000

Bare-URL WatchedItems are rolled back (CannObserv/archiver#137 step 1). Both
Archiver links become NOT NULL and the partial unique index — whose predicate
existed only to exempt bare rows — becomes a plain unique index.

Hand-written, not autogenerated: alembic emits the index predicate change
unreliably. Deploy the code that removes the bare-create paths *first*; a bare
row inserted between deploy and upgrade fails this migration.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d5a71c93e0f2"
down_revision: str | Sequence[str] | None = "bb01df9e79c8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.alter_column(
        "watched_items",
        "archiver_info_item_id",
        existing_type=sa.String(length=26),
        nullable=False,
    )
    op.alter_column(
        "watched_items",
        "archiver_info_source_id",
        existing_type=sa.String(length=26),
        nullable=False,
    )
    op.drop_index("ix_watched_items_archiver_info_item_id", table_name="watched_items")
    op.create_index(
        "ix_watched_items_archiver_info_item_id",
        "watched_items",
        ["archiver_info_item_id"],
        unique=True,
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index("ix_watched_items_archiver_info_item_id", table_name="watched_items")
    op.create_index(
        "ix_watched_items_archiver_info_item_id",
        "watched_items",
        ["archiver_info_item_id"],
        unique=True,
        postgresql_where=sa.text("archiver_info_item_id IS NOT NULL"),
    )
    op.alter_column(
        "watched_items",
        "archiver_info_source_id",
        existing_type=sa.String(length=26),
        nullable=True,
    )
    op.alter_column(
        "watched_items",
        "archiver_info_item_id",
        existing_type=sa.String(length=26),
        nullable=True,
    )
